---
- hosts: "{{ target_hosts }}"
  pre_tasks:
    - name: Add env vars
      include: env_vars.yml
      tags:
        - ImageFetcher
        - ImageService
        - deploy
  vars_files:
    - ./vars/main.yml
  roles:
    - { role: 'repo_epel', tags: ["deploy"] }
    - { role: 'nginx', tags: ["deploy"] }
    - { role: 'certtool', tags: ["deploy"] }
    - { role: 'mavenlibsextra', tags: ["ImageFetcher"] }
  tasks:
    - name: Ensure the fpm gem installed
      command: gem install fpm
      tags:
        - ImageFetcher  
        - ImageService
    - name: Setup ImageFetcher
      include: ImageFetcher.yml
      tags:
        - ImageFetcher  
    - name: Setup ImageService
      include: ImageService.yml
      tags:
        - ImageService  
    - name: Deploy ImageService and ImageFetcher
      include: deploy.yml
      tags:
        - deploy
    - name: create nginx config for cims-hrid-ui
      template:
        src: "{{ playbook_dir }}/templates/nginx/shared/image_service.conf.j2"
        dest: "/etc/nginx/shared/image_service.conf"
        mode: 0644
        backup: no
      tags:
        - deploy
    - name: Enable and start nginx
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - nginx
      tags: 
        - deploy 
