---
- hosts: "{{ target_hosts }}"
  pre_tasks:
    - name: Include production variables
      include_vars:
        file: "{{ playbook_dir }}/common/secure_vars/image_service/production.yml"
      when: deploy_env == "Production"
      tags:
        - ImageFetcher
        - ImageService
        - deploy
    - name: Include development variables
      include_vars:
        file: "{{ playbook_dir }}/common/secure_vars/image_service/development.yml"
      # when: deploy_env == "Development" || deploy_env == "Test"
      when: "deploy_env in ['Development','Test']"
      tags:
        - ImageFetcher
        - ImageService
        - deploy
  roles:
    - imageservice
